const mockEventsData = [
  {
    event_id: '1',
    title: 'Football at the Park',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Just say anything, George, say what ever's natural, the first thing that comes to your mind. Take that you mutated son-of-a-bitch. My pine, why you. You space bastard, you killed a pine. You do? Yeah, it's 8:00. Hey, McFly, I thought I told you never to come in here. Well it's gonna cost you. How much money you got on you?",
    creator: '11',
    participants: ['13', '14', '17'],
    lat: '52.520609',
    lng: '13.46016',
    min_participants: '3',
    max_participants: '10',
    tags: ['1', '2', '3'],
    address: 'Richard-Ermisch-Straße 16, 10247 Berlin \n Prenzlauer Berg Berlin Deutschland',
  },

  {
    event_id: '2',
    title: 'Ping Pong game at Codeworks',
    date_time: '2022-06-23T18:25:43.511Z',
    description: 'Yeah I know, If you put your mind to it you could accomplish anything. Who are you calling spook, pecker-wood. Leave me alone. Take care. Not a word, not a word, not a word now. Quiet, uh, donations, you want me to make a donation to the coast guard youth auxiliary?',
    creator: '13',
    participants: ['14'],
    lat: '52.520509',
    lng: '13.46036',
    min_participants: '4',
    max_participants: '4',
    tags: ['1', '2', '3'],
    address: 'Volkspark Friedrichshain, 10249 Berlin \n Friedrichshain Berlin Deutschland',
  },

  {
    event_id: '3',
    title: 'Volley-Ball Beach match',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Yeah well, you shouldn't drink. Okay, alright, Saturday is good, Saturday's good, I could spend a week in 1955. I could hang out, you could show me around. Thanks a lot, kid. Doc. Wait a minute, wait a minute, Doc, are you telling me that you built a time machine out of a delorean. Pa, what is it? What is it, Pa? I've gotta go. My god, do you know what this means? It means that this damn thing doesn't work at all. Where's Einstein, is he with you? Hey, hey listen guys. Look, I don't wanna mess with no reefer addicts, okay?",
    creator: '14',
    participants: ['16', '11', '15'],
    lat: '52.516901',
    lng: '13.361290',
    min_participants: '6',
    max_participants: '10',
    tags: ['1', '2', '3'],
    address: 'Kastanienallee, 10557 Berlin \n Tiergarten Berlin Deutschland',
  },

  {
    event_id: '4',
    title: 'Group Run and Training on the Spree',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Hey, Doc, we better back up, we don't have enough roads to get up to 88. Well uh, good, fine. Hey, hey, keep rolling, keep rolling there. No, no, no, no, this sucker's electrical. But I need a nuclear reaction to generate the one point twenty-one gigawatts of electricity that I need. What were you doing in the middle of the street, a kid your age. Marty, you seem so nervous, is something wrong?",
    creator: '14',
    participants: ['11', '13', '18', '17', '15'],
    lat: '52.535627',
    lng: '13.375854',
    min_participants: '3',
    max_participants: '8',
    tags: ['1', '2', '3'],
    address: 'Ida-Von-Arnim-Straße 3, 10115 Berlin \n Mitte Berlin Deutschland',
  },

  {
    event_id: '5',
    title: 'Coding with mates',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Thanks a lot, kid. Calm down, Marty, I didn't disintegrate anything. The molecular structure of Einstein and the car are completely intact. You got a real attitude problem, McFly. You're a slacker. You remind me of you father when he went her, he was a slacker too. About 30 years, it's a nice round number. What's going on? Where have you been all week?",
    creator: '18',
    participants: ['11', '12', '19', '15', '14'],
    lat: '52.506601',
    lng: '13.404202',
    min_participants: '8',
    max_participants: '5',
    tags: ['1', '2', '3'],
    address: 'Alte Jakobstraße 40, 10969 Berlin \n Kreuzberg Berlin Deutschland',
  },

  {
    event_id: '6',
    title: 'Walking in Kreuzberg / Sight seeing',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Just say anything, George, say what ever's natural, the first thing that comes to your mind. Take that you mutated son-of-a-bitch. My pine, why you. You space bastard, you killed a pine. You do? Yeah, it's 8:00. Hey, McFly, I thought I told you never to come in here. Well it's gonna cost you. How much money you got on you?",
    creator: '11',
    participants: ['13', '14', '17', '19'],
    lat: '52.498106',
    lng: '13.419113',
    min_participants: '7',
    max_participants: '8',
    tags: ['1', '2', '3'],
    address: 'Kottbusser Straße 24, 10999 Berlin \n Kreuzberg Berlin Deutschland',
  },

  {
    event_id: '7',
    title: 'Take a Kayak with Celine Dion',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Lynda, first of all, I'm not your answering service. Second of all, somebody named Greg or Craig called you just a little while ago. Thanks. Look, you gotta listen to me. Oh, I've been so worried about you ever since you ran off the other night. Are you okay? I'm sorry I have to go. Isn't he a dream boat? About 30 years, it's a nice round number.",
    creator: '16',
    participants: ['11', '13', '14', '17'],
    lat: '52.475527',
    lng: '13.414650',
    min_participants: '3',
    max_participants: '5',
    tags: ['1', '2', '3'],
    address: 'Oderstraße 49A, 12049 Berlin \n Neukölln Berlin Deutschland',
  },

  {
    event_id: '8',
    title: 'Kite Surfing with Mathiew at the Spree',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Mr. McFly, Mr. McFly, this just arrived, oh hi Marty. I think it's your new book. Hey not too early I sleep in Sunday's, hey McFly, you're shoe's untied, don't be so gullible, McFly. Uh, stories, science fiction stories, about visitors coming down to Earth from another planet. Then how am I supposed to ever meet anybody. Ah well, sort of.",
    creator: '19',
    participants: ['12', '14', '17'],
    lat: '52.508412',
    lng: '13.467178',
    min_participants: '4',
    max_participants: '8',
    tags: ['1', '2', '3'],
    address: 'Boxhagener Straße 81, 10245 Berlin \n Friedrichshain Berlin Deutschland',
  },

  {
    event_id: '9',
    title: 'Dancing inLine Dance with Danii ',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "The future, it's where you're going? No no no, Doc, I just got here, okay, Jennifer's here, we're gonna take the new truck for a spin. It's safe now. Everything's lead lined. Don't you lose those tapes now, we'll need a record. Wup, wup, I almost forgot my luggage. Who knows if they've got cotton underwear in the future. I'm allergic to all synthetics. Uh Doc, uh no. No, don't be silly. Excuse me.",
    creator: '12',
    participants: ['11', '13', '14', '17', '15', '18'],
    lat: '52.504585',
    lng: '13.425293',
    min_participants: '10',
    max_participants: '3',
    tags: ['1', '2', '3'],
    address: 'Mariannenplatz 1, 10997 Berlin \n Kreuzberg Berlin Deutschland',
  },

  {
    event_id: '10',
    title: 'Hinking in Berlin Alpes with Rafik',
    date_time: '2022-06-23T18:25:43.511Z',
    description: "Excuse me. Great Scott. Let me see that photograph again of your brother. Just as I thought, this proves my theory, look at your brother. Y'know this time it wasn't my fault. The Doc set all of his clocks twenty-five minutes slow. Well maybe you are and you just don't know it yet. Can't be. This is nuts. Aw, c'mon.",
    creator: '11',
    participants: ['13', '14', '17'],
    lat: '52.534015',
    lng: '13.384990',
    min_participants: '10',
    max_participants: '3',
    tags: ['1', '2', '3'],
    address: 'Schwartzkopffstraße 7L, 10115 Berlin \n Mitte Berlin Deutschland',
  },

];

export default mockEventsData;
